Microservice: # Namespace used by extractor
    Application : platform.infrastructure.prometheus_poc
    Domain      : platform
    Market      : infrastructure
    Team        : epa.enterprise-platform-engineering
                 