global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    Team: epa.enterprise-platform-engineering
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.23.13.177:9093
rule_files:
- alert-rules.yaml
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'node'
  ec2_sd_configs:
    - port: 9100
  relabel_configs:
    - source_labels:
      - '__meta_ec2_tag_environment'
      regex: 'dev'
      action: 'keep'
