---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - git:
        repo: 'https://foosball.example.org/path/to/repo.git'
        dest: /root/ansible
        clone: yes
        update: yes

    - name: Create Alertmanager configuration file
      template:
        src: alertmanager_yml.j2
        dest: /etc/alertmanager/alertmanager.yml
        owner: alertmanager
        group: alertmanager
        mode: '0644'
