---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - git:
        repo: 'https://4c6bac8df4699bf98b81f8e846781a430446638d@foosball.example.org/path/to/repo.git'
        dest: /root/ansible
        reference: test-ansible-alertmanager
        clone: yes
        update: yes
        force: yes

    - name: Create Alertmanager configuration file
      template:
        src: alertmanager_yml.j2
        dest: /etc/alertmanager/alertmanager.yml
        owner: alertmanager
        group: alertmanager
        mode: '0644'
