---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create group alertmanager for prometheus
      group:
        name: alertmanager
        state: present

    - name: Add the user 'alertmanager' with a specific uid and a primary group of 'alertmanager'
      user:
        name: alertmanager
        comment: User for alertmanager
        group: alertmanager

    - name: Get Alertmanager installation zip file
      get_url:
        url: https://github.com/prometheus/alertmanager/releases/download/v0.19.0/alertmanager-0.19.0.linux-amd64.tar.gz
        dest: /tmp/alertmanager-0.19.0.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract alertmanager installation file
      unarchive:
        src: /tmp/alertmanager-0.19.0.linux-amd64.tar.gz
        dest: /opt
        owner: alertmanager
        group: alertmanager

    - name: Copy Alertmanager executable to bin directory
      copy:
        src: /opt/alertmanager-0.19.0.linux-amd64/alertmanager
        dest: /usr/local/bin/alertmanager
        owner: alertmanager
        group: alertmanager
        mode: "0700"

    - name: Create a directory for alertmanager data
      file:
        path: /data/alertmanager
        state: directory
        owner: alertmanager
        group: alertmanager
        mode: '0700'

    - name: Create a directory for alertmanager data
      file:
        path: /etc/alertmanager
        state: directory
        owner: alertmanager
        group: alertmanager
        mode: '0700'

    - name: Create Alertmanager configuration file
      template:
        src: alertmanager_yml.j2
        dest: /etc/alertmanager/alertmanager.yml
        owner: alertmanager
        group: alertmanager
        mode: '0644'

    - name: Create Alertmanager Service file
      template:
        src: alertmanager_service.j2
        dest: /etc/systemd/system/alertmanager.service
        owner: root
        group: root
        mode: '0644'

    - name: Start service alertmanager, if not started
      service:
        name: alertmanager
        state: started
        
    - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
      cron:
        name: "Schedule alertmanager config updates"
        minute: "*/10"
        job: "ansible-playbook /root/ansible/repo/alertmanager_config_sync.yml"